CREATE TABLE cars (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  photo VARCHAR(255) NOT NULL,
  brand_id BIGINT NOT NULL,

  PRIMARY KEY(id),

  FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE
);


